server:
  applicationConnectors:
    - type: http
      port: 8080
  adminConnectors:
    - type: http
      port: 8081
      bindHost: 127.0.0.1
#logging:
#  level: DEBUG
database:
  driverClass: org.mariadb.jdbc.Driver
  user: rsapi
  password: rsapi
  url: jdbc:mariadb://localhost:3306/rsapi
  properties:
    charSet: UTF-8
workDir: ${RSAPI_WORK:-/var/rsapi}
salt: ${SALT:-dummy}
mailer:
  "@class": org.railwaystations.rsapi.mail.MockMailer
#mailer:
#  "@class": org.railwaystations.rsapi.mail.SmtpMailer
#  host: ${SMTP_HOST:-localhost}
#  port: ${SMTP_PORT:-25}
#  user: ${SMTP_USER:-}
#  passwd: ${SMTP_PASSWD:-}
#  from: ${SMTP_FROM:-}
monitor:
  "@class": org.railwaystations.rsapi.monitoring.LoggingMonitor
#  "@class": org.railwaystations.rsapi.monitoring.MatrixMonitor
#  "uploadUrl": https://matrix.org/_matrix/media/r0/upload
#  "roomUrl": ${MATRIX_ROOM_URL:-}
#  "accessToken": ${MATRIX_ACCESS_TOKEN:-}
photoBaseUrl: http://localhost:8080/photos
inboxBaseUrl: http://localhost:8080/inbox
mailVerificationUrl: http://localhost:8088/emailVerification.php?token=
mastodonBot:
  instanceUrl: https://botsin.space
  token: ${MASTODON_TOKEN:-}
  stationUrl: https://map.railway-stations.org/station.php
